### ISSUE TITLE
Mismatch psnr with paper

### ISSUE THREAD

**Issue by renhaofan** [QT-Zhu/RPBG#3]
I am trying to replicate your work, the results are as follows: 
PSNR ↑
Method | grass | hydrant | lab | pillar | road | sky | stair | Mean
3dgs  | 22.50 | 23.63 | 26.77 | 28.39 | 27.29 | 26.47 | 28.56 | 26.23
RPBG | 23.45 | 20.65 | 23.16 | 25.42 | 22.73 | 21.75 | 24.60 | 23.11

However,  in your paper,  
3dgs PSNR 25.23 
RPBG PSNR 26.33

I trained all scenes with batch size=1. I notice you mention this hyperparameter set as 8 in your paper.  I tried batch size =2, but oom in 24GB 4090.  Besides, on mill19-2,  I meet oom even with colmap point clouds as input. 

Any advice about these issues? Thanks in advance.

**Comment by QT-Zhu** [comment]
Thank you for your interest in RPBG!

- In this implementation, we use the mechanism of inner_batch, that samples an image multiple times (4 in our case), so setting batchsize=2 should be equivalent to our setting in the paper.
- Could you check the number of points in your point cloud? In my experiments, this number is around 1e6, so maybe you need to downsample the point cloud. Mill19 has rich visual textures so it's possible that the sparse reconstruction is very huge.
- I am wondering whether you have re-run the camera parameters or adopting the official ones. In my experiments, I adopt the official camera parameters as much as possible to align with previous baselines but I do observe that in some datasets, re-calibration by COLMAP will lead to better results.

Let me know if you have further problems.

**Comment by renhaofan** [comment]
| scene  | dense | sparse |  
| ------------- | ------------- | ------------- |
| grass  | 46,563,424  |141,639  |
| hydrant  | 25,419,435  |119,629  |
| lab  | 19,051,024  | 36,399 |
| pillar  | 52,336,859  |165,330  |
| road  | 60,849,229  |165,158  |
| sky  | 33,307,216  |75,547|
| stair  | 57,021,494   |153,414  |

Above is the point cloud number I generated,  oom problem raised with batch_size=2 and inner_batch=4  marked as RPBG_2x4.  So I use the RPBG_1x4.

* Following your advice, I downsample point cloud uniformly with 10 multiple to 1e6. Other hyper-parameter is the same with [here](https://github.com/QT-Zhu/RPBG/blob/main/configs/free_dataset/grass.yaml) and train_val split following with 3dgs llffhold=8.

|Method | grass | hydrant | lab | pillar | road | sky | stair | Mean |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- | ------------- |
|RPBG_1x4 | 23.45 | 20.65 | 23.16 | 25.42 | 22.73 | 21.75 | 24.60 | 23.11 |
|RPBG_2x4_with_dense_downsample10 | 22.80 | 20.44 | 22.41  | 24.81 | 23.80 | 20.81| 25.82 | 22.98  | 23.11 |

* I  have re-run the camera parameters or adopting the official ones, the point number and PSNR is similar.

| scene  | dense | sparse | 
| ------------- | ------------- | ------------- |
| grass  | 46,532,132  |141,672  |
| hydrant  | 25,450,818   |119,618  |
| lab  | 19,039,589  | 36,383 |
| pillar  | 45,948,807  |154,772  |
| road  | 60,852,590  |165,188  |
| sky  | 33,329,025  |75,453|
| stair  | 56,895,339   |153,472 |

* About 3dgs psnr on free-7. the following PSNRs of 3dgs are from official colmap results rather than generating from your scripts. Perhaps, this cause the difference with your paper.   Could you provide the point cloud of free-7 and Mill19-2 you used to generate the same results?

> I am trying to replicate your work, the results are as follows: PSNR ↑ Method | grass | hydrant | lab | pillar | road | sky | stair | Mean 3dgs | 22.50 | 23.63 | 26.77 | 28.39 | 27.29 | 26.47 | 28.56 | 26.23 RPBG | 23.45 | 20.65 | 23.16 | 25.42 | 22.73 | 21.75 | 24.60 | 23.11
> 
> However, in your paper, 3dgs PSNR 25.23 RPBG PSNR 26.33

**Comment by QT-Zhu** [comment]
I see. Btw did you encounter the problem of OOM when training 3DGS with the Free Dataset? I remember that for some scans (cannot recall the specific scans), 3DGS will cause OOM when densifying the gaussians. So I take the checkpoint when OOM occurs for evaluation.

For other details in my experiment, you are welcomed to contact me with my WeChat zqt_sunny.

**Comment by renhaofan** [comment]
Thanks for your quick response.  Yes, I meet the problem of OOM when training 3DGS in some scenes.  I found that [lazy image load](https://github.com/graphdeco-inria/gaussian-splatting/pull/58/commits/ec2d4093ba0c6be4d15533c98a4d3dd1934c10e5
) and `export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128'`  is very helpful especially in [grass, hydrant, road] scenes.
